<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ProjectExplorer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ProjectExplorer.Console/**" />
    <Compile Remove="ProjectExplorer.Blazor/**" />
    <Content Remove="ProjectExplorer.Console/**" />
    <Content Remove="ProjectExplorer.Blazor/**" />
    <None Remove="ProjectExplorer.Console/**" />
    <None Remove="ProjectExplorer.Blazor/**" />
  </ItemGroup>

</Project>
